[build]
  command = ""
  functions = "functions"
  publish = "build"

[build.environment]
  NODE_ENV="development"
  NODE_VERSION = "14"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "*"
  [headers.values]
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=604800, s-max-age=604800"

[[headers]]
  for = "/*.(png|jpg|js|css|svg|woff|ttf|eot|ico|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-max-age=31536000"
