name: Hourly Events Check

on:
  schedule:
    - cron:  '30 * * * *'

jobs:
  hourly_events_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Report
      env:
        SLACK_CHANNEL: "#announcements"
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      run: bundle exec rake virtual_coffee_bot:next_event
