---
name: Testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test against Ruby 2.7

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundle: true
    - name: Install Gems
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec
